
set(FILES
    Include/RenderJoy/RenderJoyCommon.h
    Include/RenderJoy/RenderJoySettingsBus.h
    Include/RenderJoy/RenderJoyTextureProviderBus.h
    Include/RenderJoy/RenderJoyPassBus.h
    Include/RenderJoy/IRenderJoySrgDataProvider.h
    Include/RenderJoy/RenderJoyKeyboardBus.h
    Source/Tools/RenderJoyEditorSystemComponent.cpp
    Source/Tools/RenderJoyEditorSystemComponent.h
    Source/Tools/Components/RenderJoySettingsEditorComponent.cpp
    Source/Tools/Components/RenderJoySettingsEditorComponent.h
    Source/Tools/Components/RenderJoyPassEditorComponent.cpp
    Source/Tools/Components/RenderJoyPassEditorComponent.h
    Source/Tools/Components/RenderJoyTextureEditorComponent.cpp
    Source/Tools/Components/RenderJoyTextureEditorComponent.h
    Source/Tools/Components/RenderJoyKeyboardEditorComponent.cpp
    Source/Tools/Components/RenderJoyKeyboardEditorComponent.h
    Source/Render/RenderJoyTrianglePass.cpp
    Source/Render/RenderJoyTrianglePass.h
    Source/Render/RenderJoyMainPassTemplateCreator.cpp
    Source/Render/RenderJoyMainPassTemplateCreator.h
)
