
set(FILES
    Include/RenderJoy/RenderJoyCommon.h
    Include/RenderJoy/RenderJoySettingsBus.h
    Include/RenderJoy/RenderJoyTextureProviderBus.h
    Include/RenderJoy/RenderJoyPassBus.h
    Include/RenderJoy/IRenderJoySrgDataProvider.h
    Include/RenderJoy/RenderJoyKeyboardBus.h
    Include/RenderJoy/Document/RenderJoyCanvasDocumentNotificationBus.h
    Include/RenderJoy/Document/RenderJoyCanvasDocumentRequestBus.h
    Include/RenderJoy/RenderJoyCanvasWindowRequestBus.h
    Include/RenderJoy/RenderJoyCanvasSystemRequestBus.h
    Source/RenderJoyEditorSystemComponent.cpp
    Source/RenderJoyEditorSystemComponent.h
    Source/MainWindow.cpp
    Source/MainWindow.h
    Source/RenderJoyTrianglePass.cpp
    Source/RenderJoyTrianglePass.h
    Source/RenderJoyMainPassTemplateCreator.cpp
    Source/RenderJoyMainPassTemplateCreator.h
    Source/Viewport/RenderJoyViewportRenderer.cpp
    Source/Viewport/RenderJoyViewportRenderer.h
    Source/Viewport/RenderJoyViewportWidget.cpp
    Source/Viewport/RenderJoyViewportWidget.h
    Source/Viewport/RenderJoyViewportWidget.ui
    Source/Components/RenderJoySettingsEditorComponent.cpp
    Source/Components/RenderJoySettingsEditorComponent.h
    Source/Components/RenderJoyPassEditorComponent.cpp
    Source/Components/RenderJoyPassEditorComponent.h
    Source/Components/RenderJoyTextureEditorComponent.cpp
    Source/Components/RenderJoyTextureEditorComponent.h
    Source/Components/RenderJoyKeyboardEditorComponent.cpp
    Source/Components/RenderJoyKeyboardEditorComponent.h
    Source/Canvas/RenderJoyCanvasWindow.cpp
    Source/Canvas/RenderJoyCanvasWindow.h
    Source/Canvas/RenderJoyCanvasGraphView.cpp
    Source/Canvas/RenderJoyCanvasGraphView.h
    Source/Canvas/Document/RenderJoyCanvasDocument.cpp
    Source/Canvas/Document/RenderJoyCanvasDocument.h
)
